/**
 * EatBy design tokens — from specs/stitch_eatby_design/minimalist_utility_inventory/DESIGN.md
 */
export const Colors = {
  surface: "#f4fbf4",
  surfaceDim: "#d4dcd5",
  surfaceBright: "#f4fbf4",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#eef6ee",
  surfaceContainer: "#e8f0e9",
  surfaceContainerHigh: "#e3eae3",
  surfaceContainerHighest: "#dde4dd",
  onSurface: "#161d19",
  onSurfaceVariant: "#3c4a42",
  inverseSurface: "#2b322d",
  inverseOnSurface: "#ebf3eb",
  outline: "#6c7a71",
  outlineVariant: "#bbcabf",
  surfaceTint: "#006c49",
  primary: "#006c49",
  onPrimary: "#ffffff",
  primaryContainer: "#10b981",
  onPrimaryContainer: "#00422b",
  inversePrimary: "#4edea3",
  secondary: "#b61722",
  onSecondary: "#ffffff",
  secondaryContainer: "#da3437",
  onSecondaryContainer: "#fffbff",
  tertiary: "#855300",
  onTertiary: "#ffffff",
  tertiaryContainer: "#e29100",
  onTertiaryContainer: "#523200",
  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",
  primaryFixed: "#6ffbbe",
  primaryFixedDim: "#4edea3",
  onPrimaryFixed: "#002113",
  onPrimaryFixedVariant: "#005236",
  secondaryFixed: "#ffdad7",
  secondaryFixedDim: "#ffb3ad",
  onSecondaryFixed: "#410004",
  onSecondaryFixedVariant: "#930013",
  tertiaryFixed: "#ffddb8",
  tertiaryFixedDim: "#ffb95f",
  onTertiaryFixed: "#2a1700",
  onTertiaryFixedVariant: "#653e00",
  background: "#f4fbf4",
  onBackground: "#161d19",
  surfaceVariant: "#dde4dd",
} as const;

export type ColorKey = keyof typeof Colors;
